// Emit the valdi_module BUILD - reference-verified green shape (end-to-end proofs:
// iOS on @capacitor/device + @capacitor/preferences + test_events through
// ios_deps; Android on the same trio through android_deps - the impl
// (valdi_android_library: <module>_android_impl) is exported by the module's
// <module>_kt target, mirroring valdi_webview's own BUILD).

export function emitBazel(model, moduleName, moduleClass, hasSwift, hasJava, androidPkg = 'com.plugin2valdi.modules') {
  const swiftModule = moduleClass.replace(/Module$/, '') + 'Conformance';
  return [
    `# plugin2valdi generated BUILD.bazel - verified green contract shape`,
    `load("@valdi//bzl/valdi:valdi_module.bzl", "valdi_module")`,
    ...(hasJava ? [`load("@valdi//bzl/valdi:valdi_android_library.bzl", "valdi_android_library")`] : []),
    ``,
    `valdi_module(`,
    `    name = "${moduleName}",`,
    `    # tsconfig.json must be in srcs: without it the Valdi compiler emits`,
    `    # only .d.ts for the module and packs no compiled JS into the`,
    `    # .valdimodule - the app then dies at runtime with`,
    `    # "No item named '<module>/src/*.js' in module '...'"`,
    `    srcs = glob([`,
    `        "src/**/*.ts",`,
    `        "src/**/*.tsx",`,
    `    ]) + ["tsconfig.json"],`,
    `    android_class_path = "${androidPkg}.${moduleName}",`,
    ...(hasJava ? [
      `    # Android impl (conformance): the Java implementation + Kotlin factory`,
      `    # are exported from :${moduleName}_kt - same wiring valdi_webview uses`,
      `    # for its own android impl.`,
      `    android_deps = [":${moduleName}_android_impl"],`,
    ] : []),
    ...(hasSwift ? [
      `    # Conformance (blocked upstream in Valdi beta-0.1.1 - three-part`,
      `    # Swift interop defect chain; findings in FLAGS.md). Uncomment when fixed:`,
      `    ios_deps = [":${moduleName}_conformance", ":${moduleName}_factory"],`,
    ] : []),
    `    visibility = ["//visibility:public"],`,
    `    deps = [`,
    `        "@valdi//src/valdi_modules/src/valdi/valdi_core",`,
    `    ],`,
    `)`,
    ...(hasJava ? [
      ``,
      `# Android implementation: generated-Kotlin interface implementor (${moduleClass}ModuleImpl,`,
      `# package-private - a public class would collide with the interface), the`,
      `# @RegisterValdiModule Kotlin factory (annotation processor emits the`,
      `# assets/valdi_native_modules manifest entry), and copied bridge-free`,
      `# plugin helpers. kt_android_library compiles mixed .kt/.java sources.`,
      `valdi_android_library(`,
      `    name = "${moduleName}_android_impl",`,
      `    srcs = glob([`,
      `        "android/**",`,
      `    ]),`,
      `    visibility = ["//visibility:public"],`,
      `    deps = [`,
      `        ":${moduleName}_api_kt",`,
      `        "@valdi//valdi:valdi_java",`,
      `    ],`,
      `)`,
    ] : []),
    ...(hasSwift ? [
      ``,
      `# Conformance targets (blocked upstream - uncomment + fix imports when Swift`,
      `# visibility for user modules lands):`,
      `load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")`,
      `load("@valdi//bzl:modulemap.bzl", "modulemap")`,
      `swift_library(`,
      `    name = "${moduleName}_conformance",`,
      `    srcs = ["ios/${moduleName}_conformance.swift", "ios/${moduleName}_support.swift"],`,
      `    module_name = "${swiftModule}",`,
      `    generates_header = True,`,
      `    target_compatible_with = ["@platforms//os:ios"],`,
      `    deps = [":${moduleName}_api_objc", "@valdi//valdi_core:valdi_core_objc"],`,
      `)`,
      `modulemap(`,
      `    name = "${moduleName}_conformance_map",`,
      `    hdrs = [":${moduleName}_conformance"],`,
      `    module_name = "${swiftModule}",`,
      `)`,
      ``,
      `objc_library(`,
      `    name = "${moduleName}_factory",`,
      `    srcs = ["ios/${moduleName}_factory.m"],`,
      `    copts = ["-I.", "-fmodules"],`,
      `    target_compatible_with = ["@platforms//os:ios"],`,
      `    deps = [":${moduleName}_api_objc", ":${moduleName}_conformance", "@valdi//valdi_core:valdi_core_objc"],`,
      `)`,
    ] : []),
    ``,
  ].join('\n');
}
